default_install_hook_types: [pre-push]
default_stages: [pre-push]
repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["-v", "tests/"]
        stages: [pre-push]
