default_install_hook_types: [pre-push]
default_stages: [pre-push]
repos:
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: make
        language: system
        pass_filenames: false
        always_run: true
        args: ["pre-commit"]
        stages: [pre-push]
