
services:
  redis:
    image: redis:7.2.3-alpine
    container_name: test-das-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongodb:
    image: mongo:latest
    container_name: test-das-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          'db.runCommand("ping").ok',
          "|",
          "mongo",
          "das-mongo:27017/test",
          "--quiet",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s


  metta-parser:
#    image: trueagi/das:latest-metta-parser
#    image: trueagi/das:0.5.3-metta-parser
    image: trueagi/das:0.5.4-metta-parser
#    build:
#      context: https://github.com/singnet/das-metta-parser.git#master:docker
#    build: docker_metta_parser
    container_name: test-das-metta-parser
    working_dir: /opt/das-metta-parser
    command: db_loader /tmp/animals.metta
#    command: sleep infinity
    network_mode: "host"

    volumes:
      - ./examples/data:/tmp
    environment:
      DAS_MONGODB_NAME: das
      DAS_MONGODB_HOSTNAME: localhost
      DAS_MONGODB_PORT: 27017
      DAS_REDIS_HOSTNAME: localhost
      DAS_REDIS_PORT: 6379
      DAS_MONGODB_USERNAME: root
      DAS_MONGODB_PASSWORD: root
      DAS_DATABASE_USERNAME: root
      DAS_DATABASE_PASSWORD: root
#    env_file:
#      - .env
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure

  das-attention-broker:
    # How to build:
    # Clone the das-node repository
    # Run:
    # ./scripts/docker_image_build.sh
    build: ./docker_das_node
    container_name: test-das-attention-broker
    command: ./bin/attention_broker 37007
    network_mode: host
    ports:
      - 35700:35700
    depends_on:
      - mongodb
      - redis
      - metta-parser
    restart: on-failure
    environment:
      DAS_MONGODB_NAME: das
      DAS_MONGODB_HOSTNAME: localhost
      DAS_MONGODB_PORT: 27017
      DAS_REDIS_HOSTNAME: localhost
      DAS_REDIS_PORT: 6379
      DAS_MONGODB_USERNAME: root
      DAS_MONGODB_PASSWORD: root

  das-node:
    # How to build:
    # Clone the das-node repository
    # Run:
    # ./scripts/docker_image_build.sh
    build: ./docker_das_node
    container_name: test-das-node
    command: ./bin/query_broker 35700
    network_mode: host
    ports:
      - 35700:35700
    restart: on-failure
    depends_on:
      - mongodb
      - redis
      - metta-parser
      - das-attention-broker
    environment:
      DAS_MONGODB_NAME: das
      DAS_MONGODB_HOSTNAME: localhost
      DAS_MONGODB_PORT: 27017
      DAS_REDIS_HOSTNAME: localhost
      DAS_REDIS_PORT: 6379
      DAS_MONGODB_USERNAME: root
      DAS_MONGODB_PASSWORD: root

  fass:
#    image: trueagi/openfaas:query-engine-1.14.12
    image: trueagi/openfaas:query-engine-1.14.13
#    image: trueagi/openfaas:query-engine-latest
    container_name: test-das-faas
#    privileged: true
    depends_on:
      - mongodb
      - redis
      - metta-parser
      - das-node
    ports:
      - 8080:8080
    environment:
      DAS_MONGODB_NAME: test-das
      DAS_MONGODB_HOSTNAME: test-das-mongodb
      DAS_MONGODB_PORT: 27017
      DAS_REDIS_HOSTNAME: test-das-redis
      DAS_REDIS_PORT: 6379
      DAS_MONGODB_USERNAME: root
      DAS_MONGODB_PASSWORD: root
      DAS_DATABASE_USERNAME: root
      DAS_DATABASE_PASSWORD: root


        

