# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attention_broker.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import hyperon_das.grpc.common_pb2 as common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16\x61ttention_broker.proto\x12\x03\x64\x61s\x1a\x0c\x63ommon.proto2\x86\x01\n\x0f\x41ttentionBroker\x12\x1e\n\x04ping\x12\n.das.Empty\x1a\x08.das.Ack\"\x00\x12)\n\tstimulate\x12\x10.das.HandleCount\x1a\x08.das.Ack\"\x00\x12(\n\tcorrelate\x12\x0f.das.HandleList\x1a\x08.das.Ack\"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'attention_broker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_ATTENTIONBROKER']._serialized_start = 46
    _globals['_ATTENTIONBROKER']._serialized_end = 180
# @@protoc_insertion_point(module_scope)
