---
name: Testing

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ^3.8.5

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pip3 install poetry

      - name: Run poetry lock
        run: poetry lock --no-update 

      - name: Install dependencies
        run: poetry export --dev -f requirements.txt | pip3 install -r /dev/stdin

      - name: Run Unit Tests
        run: make unit-tests unit-tests-coverage

      - name:
        run: make integration-tests
